### PR TITLE
Updating vital information

### PR DESCRIPTION
**Pull request by Tokukarin**

### CODE REVIEW

**Comment by wh1te909** [comment]
https://docs.tacticalrmm.com/code_signing/ and https://docs.tacticalrmm.com/faq/#linuxmacos-agents

**Comment by Tokukarin** [comment]
@wh1te909 ? Should it not be mentioned on a requirements page or on the readme that this open source software is not working OOTB without paying?

**Comment by bbrendon** [comment]
@Tokukarin You can install the linux agent without paying. It just not turnkey.

**Comment by wh1te909** [comment]
TacticalRMM is not "open source". Open source is a legal term, it has nothing to do with source code. 

Tactical RMM is source available, as is clearly stated on our documentation page and license. Sounds like you didn't read the docs: https://docs.tacticalrmm.com

Our source code is 100% available on github. You are welcome to read through it and compile your own windows/linux/mac agents if you want.

If you want the convenience of pre-compiled agents, you need to pay for that. Otherwise you can do it yourself.

**Comment by Tokukarin** [comment]
@bbrendon May I ask how so?

@wh1te909 I read the docs, but not the license, those are like AGB/GTC you just click accept.
But now I understand, GitHub projects are always fishy when a company is behind it.

**Comment by wh1te909** [comment]
Yes sorry we turned out to be a fishy company. Sounds like you should go with the other free open source RMM softwares out there. Sorry to disappoint!

**Comment by wh1te909** [comment]
🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡 🐟 🐡

**Pull request closed without merging**
