### PR TITLE
update docker for stability and flexibility

### PR DESCRIPTION
**Pull request by ninjamonkey198206**
Updated docker-compose and env files to allow for multiple instances to run simultaneously on the same system, to prep for HA/failover and serving multiple domains. Fleshed out network definitions to prevent random network issues and allow for simpler host firewall config.

### CODE REVIEW

**Comment by sadnub** [comment]
I looked through the changes and the post aliases look good for mesh. I'm not sure we need to hardcode the docker networks though. I have been meaning to remove the need to hardcode the proxy network.

I also would like to use COMPOSE_PROJECT_NAME so that it will prefix all docker assets. I'm just not sure how this will affect upgrades and if existing volumes will map correctly

**Comment by ninjamonkey198206** [comment]
The variables to set the network info, and fleshing them out fully in general, was to solve intermittent issues I was having, like the network showing as up but with no gateway (it was weird). The network names are to specify the name used in firewalls, like IPTables, instead of BR-xxxxxxxxxx that may need to have ports opened to. It's for edge case uses like mine, were I have drop all by default firewall rules, or when you're running HAProxy on the same system. Just easier to make the rules because that name won't change if you don't manually change it.

The issues are probably with Dockers network stack to be honest, just found that those worked to prevent the issues from coming up.

**Comment by ninjamonkey198206** [comment]
Also why I figured having defaults in place would make it easier to just edit and go. Most people wouldn't need to change them.

Not sure what COMPOSE_PROJECT_NAME is.
I put the prefix in with T-RMM as default so if folks wanted to run multiple instances after websockets are in place, they could just edit the prefix env, network info, and other basics and go.

How would the compose project thing do that? Rather, what would it be based on? Still new to this side of Docker, so I've got holes in my knowledge base.

**Comment by ninjamonkey198206** [comment]
Ah, just looked that up. I can change it to compose project name. Didn't know that was already a thing. It's just set in the env file like the other variables, correct?

**Comment by ninjamonkey198206** [comment]
Using the compose project name might require manually (or via scripting) moving the files from the existing volumes to new ones, but it would be possible and fairly simple.

**Comment by ninjamonkey198206** [comment]
@sadnub So how do you want me to proceed with this?

**Comment by ninjamonkey198206** [comment]
Need to update and modify for new settings, and it's being a PITA

**Pull request closed without merging**
