### PR TITLE
sso init

### PR DESCRIPTION
**Pull request by sadnub**

### CODE REVIEW

**Comment by jbonor** [comment]
Anyone working on this?

**Comment by wh1te909** [comment]
> Anyone working on this?

are you blind?

**Comment by jbonor** [comment]
> > Anyone working on this?
> 
> are you blind?

So it seems, didn't notice the recent push. What I really wanted to know is if this has any chance of being in a future version.

**Comment by wh1te909** [comment]
it will be in the next release which if testing goes well will be sometime this week

**Comment by P6g9YHK6** [comment]
> it will be in the next release which if testing goes well will be sometime this week

Valve time strikes again ? 😘

**Pull request merged**
