### PR TITLE
Update agent_linux.sh

### PR DESCRIPTION
**Pull request by dinger1986**
for usage like this ./install_script.sh --binpath /my/custom/path

to close this issue https://github.com/amidaware/tacticalrmm/issues/1508

### CODE REVIEW

**Comment by wh1te909** [comment]
doesn't work, i tested like this `./agent.sh --binpath /opt/trmmtest` and still installed to /usr/local/bin

**Comment by dinger1986** [comment]
I'll check it and sort it

**Comment by dinger1986** [comment]
sorted, hadnt copied up $2 for some reason sorry!

image

**Comment by wh1te909** [comment]
thanks now just uninstall doesn't cleanup properly, binary is still left behind.

**Comment by dinger1986** [comment]
its actually not right anyway, what I have done is basically accept the second argument when running the script as the binpath and thats not right, let me look at it a bit more

**Comment by dinger1986** [comment]
reordered alot of parts and added command to find bin location from service file, tested working on debian 11 and 12

**Pull request closed without merging**
