### PR TITLE
initial SysTray api PR

### PR DESCRIPTION
**Pull request by conlan0**
- Added celery task to send nats command to agent every 5 mins to update systray
- Added site-based json tray configs
- Added global toggle for systray to be enabled
- Added agent api communication for config, status, icon and name

### CODE REVIEW

**Comment by conlan0** [comment]
no i need to add my migrations here too?

**Comment by wh1te909** [comment]
yes migrations need to be added

**Comment by conlan0** [comment]
how do i fix these errors

**Comment by wh1te909** [comment]
look at the test failures to see what it's complaining about, in this case you need to format your code with [black](https://github.com/psf/black)

The systray should be it's own django app, not under apiv3 so please move it out of there. You can still write the views under `apiv3/views.py`. Also makes more sense to name the app `systray` instead of `support`. Run `python manage.py startapp systray` under the project root. You'll need to delete and recreate your migrations and adjust imports etc.

**Comment by conlan0** [comment]
Okay awesome thanks, will take care of those and get it updated!

**Pull request closed without merging**
