### PR TITLE
Update views.py

### PR DESCRIPTION
**Pull request by dinger1986**
add mesh company name to initial setup

### CODE REVIEW

**Comment by dinger1986** [comment]
I assume this is failing due to it not knowing what companyname is but thats pulled from the frontend?

**Comment by wh1te909** [comment]
the tests need to be updated as well, see https://github.com/amidaware/tacticalrmm/pull/1810/checks#step:10:979
we fake the data from the frontend with our unit tests so just need to add a company name to the payload

**Comment by dinger1986** [comment]
so added to tests.py is that right? will it run against that or does the tests.py need pr'd first?

**Comment by dinger1986** [comment]
forgot the `,`

**Comment by wh1te909** [comment]
yup tests are passing now

**Pull request merged**
